// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/switchboard/domain"
)

type FakeBridge struct {
	ConnectStub        func()
	connectMutex       sync.RWMutex
	connectArgsForCall []struct{}
	CloseStub          func()
	closeMutex         sync.RWMutex
	closeArgsForCall   []struct{}
}

func (fake *FakeBridge) Connect() {
	fake.connectMutex.Lock()
	fake.connectArgsForCall = append(fake.connectArgsForCall, struct{}{})
	fake.connectMutex.Unlock()
	if fake.ConnectStub != nil {
		fake.ConnectStub()
	}
}

func (fake *FakeBridge) ConnectCallCount() int {
	fake.connectMutex.RLock()
	defer fake.connectMutex.RUnlock()
	return len(fake.connectArgsForCall)
}

func (fake *FakeBridge) Close() {
	fake.closeMutex.Lock()
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct{}{})
	fake.closeMutex.Unlock()
	if fake.CloseStub != nil {
		fake.CloseStub()
	}
}

func (fake *FakeBridge) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

var _ domain.Bridge = new(FakeBridge)
