// This file was generated by counterfeiter
package domainfakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/switchboard/domain"
)

type FakeBackends struct {
	AllStub        func() <-chan domain.Backend
	allMutex       sync.RWMutex
	allArgsForCall []struct{}
	allReturns     struct {
		result1 <-chan domain.Backend
	}
	SetHealthyStub        func(backend domain.Backend)
	setHealthyMutex       sync.RWMutex
	setHealthyArgsForCall []struct {
		backend domain.Backend
	}
	SetUnhealthyStub        func(backend domain.Backend)
	setUnhealthyMutex       sync.RWMutex
	setUnhealthyArgsForCall []struct {
		backend domain.Backend
	}
	AsJSONStub        func() []domain.BackendJSON
	asJSONMutex       sync.RWMutex
	asJSONArgsForCall []struct{}
	asJSONReturns     struct {
		result1 []domain.BackendJSON
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBackends) All() <-chan domain.Backend {
	fake.allMutex.Lock()
	fake.allArgsForCall = append(fake.allArgsForCall, struct{}{})
	fake.recordInvocation("All", []interface{}{})
	fake.allMutex.Unlock()
	if fake.AllStub != nil {
		return fake.AllStub()
	} else {
		return fake.allReturns.result1
	}
}

func (fake *FakeBackends) AllCallCount() int {
	fake.allMutex.RLock()
	defer fake.allMutex.RUnlock()
	return len(fake.allArgsForCall)
}

func (fake *FakeBackends) AllReturns(result1 <-chan domain.Backend) {
	fake.AllStub = nil
	fake.allReturns = struct {
		result1 <-chan domain.Backend
	}{result1}
}

func (fake *FakeBackends) SetHealthy(backend domain.Backend) {
	fake.setHealthyMutex.Lock()
	fake.setHealthyArgsForCall = append(fake.setHealthyArgsForCall, struct {
		backend domain.Backend
	}{backend})
	fake.recordInvocation("SetHealthy", []interface{}{backend})
	fake.setHealthyMutex.Unlock()
	if fake.SetHealthyStub != nil {
		fake.SetHealthyStub(backend)
	}
}

func (fake *FakeBackends) SetHealthyCallCount() int {
	fake.setHealthyMutex.RLock()
	defer fake.setHealthyMutex.RUnlock()
	return len(fake.setHealthyArgsForCall)
}

func (fake *FakeBackends) SetHealthyArgsForCall(i int) domain.Backend {
	fake.setHealthyMutex.RLock()
	defer fake.setHealthyMutex.RUnlock()
	return fake.setHealthyArgsForCall[i].backend
}

func (fake *FakeBackends) SetUnhealthy(backend domain.Backend) {
	fake.setUnhealthyMutex.Lock()
	fake.setUnhealthyArgsForCall = append(fake.setUnhealthyArgsForCall, struct {
		backend domain.Backend
	}{backend})
	fake.recordInvocation("SetUnhealthy", []interface{}{backend})
	fake.setUnhealthyMutex.Unlock()
	if fake.SetUnhealthyStub != nil {
		fake.SetUnhealthyStub(backend)
	}
}

func (fake *FakeBackends) SetUnhealthyCallCount() int {
	fake.setUnhealthyMutex.RLock()
	defer fake.setUnhealthyMutex.RUnlock()
	return len(fake.setUnhealthyArgsForCall)
}

func (fake *FakeBackends) SetUnhealthyArgsForCall(i int) domain.Backend {
	fake.setUnhealthyMutex.RLock()
	defer fake.setUnhealthyMutex.RUnlock()
	return fake.setUnhealthyArgsForCall[i].backend
}

func (fake *FakeBackends) AsJSON() []domain.BackendJSON {
	fake.asJSONMutex.Lock()
	fake.asJSONArgsForCall = append(fake.asJSONArgsForCall, struct{}{})
	fake.recordInvocation("AsJSON", []interface{}{})
	fake.asJSONMutex.Unlock()
	if fake.AsJSONStub != nil {
		return fake.AsJSONStub()
	} else {
		return fake.asJSONReturns.result1
	}
}

func (fake *FakeBackends) AsJSONCallCount() int {
	fake.asJSONMutex.RLock()
	defer fake.asJSONMutex.RUnlock()
	return len(fake.asJSONArgsForCall)
}

func (fake *FakeBackends) AsJSONReturns(result1 []domain.BackendJSON) {
	fake.AsJSONStub = nil
	fake.asJSONReturns = struct {
		result1 []domain.BackendJSON
	}{result1}
}

func (fake *FakeBackends) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.allMutex.RLock()
	defer fake.allMutex.RUnlock()
	fake.setHealthyMutex.RLock()
	defer fake.setHealthyMutex.RUnlock()
	fake.setUnhealthyMutex.RLock()
	defer fake.setUnhealthyMutex.RUnlock()
	fake.asJSONMutex.RLock()
	defer fake.asJSONMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeBackends) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.Backends = new(FakeBackends)
