// This file was generated by counterfeiter
package domainfakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/switchboard/domain"
)

type FakeArpManager struct {
	ClearCacheStub        func(ip string) error
	clearCacheMutex       sync.RWMutex
	clearCacheArgsForCall []struct {
		ip string
	}
	clearCacheReturns struct {
		result1 error
	}
	IsCachedStub        func(ip string) bool
	isCachedMutex       sync.RWMutex
	isCachedArgsForCall []struct {
		ip string
	}
	isCachedReturns struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeArpManager) ClearCache(ip string) error {
	fake.clearCacheMutex.Lock()
	fake.clearCacheArgsForCall = append(fake.clearCacheArgsForCall, struct {
		ip string
	}{ip})
	fake.recordInvocation("ClearCache", []interface{}{ip})
	fake.clearCacheMutex.Unlock()
	if fake.ClearCacheStub != nil {
		return fake.ClearCacheStub(ip)
	} else {
		return fake.clearCacheReturns.result1
	}
}

func (fake *FakeArpManager) ClearCacheCallCount() int {
	fake.clearCacheMutex.RLock()
	defer fake.clearCacheMutex.RUnlock()
	return len(fake.clearCacheArgsForCall)
}

func (fake *FakeArpManager) ClearCacheArgsForCall(i int) string {
	fake.clearCacheMutex.RLock()
	defer fake.clearCacheMutex.RUnlock()
	return fake.clearCacheArgsForCall[i].ip
}

func (fake *FakeArpManager) ClearCacheReturns(result1 error) {
	fake.ClearCacheStub = nil
	fake.clearCacheReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeArpManager) IsCached(ip string) bool {
	fake.isCachedMutex.Lock()
	fake.isCachedArgsForCall = append(fake.isCachedArgsForCall, struct {
		ip string
	}{ip})
	fake.recordInvocation("IsCached", []interface{}{ip})
	fake.isCachedMutex.Unlock()
	if fake.IsCachedStub != nil {
		return fake.IsCachedStub(ip)
	} else {
		return fake.isCachedReturns.result1
	}
}

func (fake *FakeArpManager) IsCachedCallCount() int {
	fake.isCachedMutex.RLock()
	defer fake.isCachedMutex.RUnlock()
	return len(fake.isCachedArgsForCall)
}

func (fake *FakeArpManager) IsCachedArgsForCall(i int) string {
	fake.isCachedMutex.RLock()
	defer fake.isCachedMutex.RUnlock()
	return fake.isCachedArgsForCall[i].ip
}

func (fake *FakeArpManager) IsCachedReturns(result1 bool) {
	fake.IsCachedStub = nil
	fake.isCachedReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeArpManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.clearCacheMutex.RLock()
	defer fake.clearCacheMutex.RUnlock()
	fake.isCachedMutex.RLock()
	defer fake.isCachedMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeArpManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.ArpManager = new(FakeArpManager)
