// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/pivotal-cf-experimental/switchboard"
)

type FakeBackends struct {
	AllStub        func() <-chan switchboard.Backend
	allMutex       sync.RWMutex
	allArgsForCall []struct{}
	allReturns struct {
		result1 <-chan switchboard.Backend
	}
	AnyStub        func() switchboard.Backend
	anyMutex       sync.RWMutex
	anyArgsForCall []struct{}
	anyReturns struct {
		result1 switchboard.Backend
	}
	ActiveStub        func() switchboard.Backend
	activeMutex       sync.RWMutex
	activeArgsForCall []struct{}
	activeReturns struct {
		result1 switchboard.Backend
	}
	SetHealthyStub        func(backend switchboard.Backend)
	setHealthyMutex       sync.RWMutex
	setHealthyArgsForCall []struct {
		backend switchboard.Backend
	}
	SetUnhealthyStub        func(backend switchboard.Backend)
	setUnhealthyMutex       sync.RWMutex
	setUnhealthyArgsForCall []struct {
		backend switchboard.Backend
	}
	HealthyStub        func() <-chan switchboard.Backend
	healthyMutex       sync.RWMutex
	healthyArgsForCall []struct{}
	healthyReturns struct {
		result1 <-chan switchboard.Backend
	}
}

func (fake *FakeBackends) All() <-chan switchboard.Backend {
	fake.allMutex.Lock()
	fake.allArgsForCall = append(fake.allArgsForCall, struct{}{})
	fake.allMutex.Unlock()
	if fake.AllStub != nil {
		return fake.AllStub()
	} else {
		return fake.allReturns.result1
	}
}

func (fake *FakeBackends) AllCallCount() int {
	fake.allMutex.RLock()
	defer fake.allMutex.RUnlock()
	return len(fake.allArgsForCall)
}

func (fake *FakeBackends) AllReturns(result1 <-chan switchboard.Backend) {
	fake.AllStub = nil
	fake.allReturns = struct {
		result1 <-chan switchboard.Backend
	}{result1}
}

func (fake *FakeBackends) Any() switchboard.Backend {
	fake.anyMutex.Lock()
	fake.anyArgsForCall = append(fake.anyArgsForCall, struct{}{})
	fake.anyMutex.Unlock()
	if fake.AnyStub != nil {
		return fake.AnyStub()
	} else {
		return fake.anyReturns.result1
	}
}

func (fake *FakeBackends) AnyCallCount() int {
	fake.anyMutex.RLock()
	defer fake.anyMutex.RUnlock()
	return len(fake.anyArgsForCall)
}

func (fake *FakeBackends) AnyReturns(result1 switchboard.Backend) {
	fake.AnyStub = nil
	fake.anyReturns = struct {
		result1 switchboard.Backend
	}{result1}
}

func (fake *FakeBackends) Active() switchboard.Backend {
	fake.activeMutex.Lock()
	fake.activeArgsForCall = append(fake.activeArgsForCall, struct{}{})
	fake.activeMutex.Unlock()
	if fake.ActiveStub != nil {
		return fake.ActiveStub()
	} else {
		return fake.activeReturns.result1
	}
}

func (fake *FakeBackends) ActiveCallCount() int {
	fake.activeMutex.RLock()
	defer fake.activeMutex.RUnlock()
	return len(fake.activeArgsForCall)
}

func (fake *FakeBackends) ActiveReturns(result1 switchboard.Backend) {
	fake.ActiveStub = nil
	fake.activeReturns = struct {
		result1 switchboard.Backend
	}{result1}
}

func (fake *FakeBackends) SetHealthy(backend switchboard.Backend) {
	fake.setHealthyMutex.Lock()
	fake.setHealthyArgsForCall = append(fake.setHealthyArgsForCall, struct {
		backend switchboard.Backend
	}{backend})
	fake.setHealthyMutex.Unlock()
	if fake.SetHealthyStub != nil {
		fake.SetHealthyStub(backend)
	}
}

func (fake *FakeBackends) SetHealthyCallCount() int {
	fake.setHealthyMutex.RLock()
	defer fake.setHealthyMutex.RUnlock()
	return len(fake.setHealthyArgsForCall)
}

func (fake *FakeBackends) SetHealthyArgsForCall(i int) switchboard.Backend {
	fake.setHealthyMutex.RLock()
	defer fake.setHealthyMutex.RUnlock()
	return fake.setHealthyArgsForCall[i].backend
}

func (fake *FakeBackends) SetUnhealthy(backend switchboard.Backend) {
	fake.setUnhealthyMutex.Lock()
	fake.setUnhealthyArgsForCall = append(fake.setUnhealthyArgsForCall, struct {
		backend switchboard.Backend
	}{backend})
	fake.setUnhealthyMutex.Unlock()
	if fake.SetUnhealthyStub != nil {
		fake.SetUnhealthyStub(backend)
	}
}

func (fake *FakeBackends) SetUnhealthyCallCount() int {
	fake.setUnhealthyMutex.RLock()
	defer fake.setUnhealthyMutex.RUnlock()
	return len(fake.setUnhealthyArgsForCall)
}

func (fake *FakeBackends) SetUnhealthyArgsForCall(i int) switchboard.Backend {
	fake.setUnhealthyMutex.RLock()
	defer fake.setUnhealthyMutex.RUnlock()
	return fake.setUnhealthyArgsForCall[i].backend
}

func (fake *FakeBackends) Healthy() <-chan switchboard.Backend {
	fake.healthyMutex.Lock()
	fake.healthyArgsForCall = append(fake.healthyArgsForCall, struct{}{})
	fake.healthyMutex.Unlock()
	if fake.HealthyStub != nil {
		return fake.HealthyStub()
	} else {
		return fake.healthyReturns.result1
	}
}

func (fake *FakeBackends) HealthyCallCount() int {
	fake.healthyMutex.RLock()
	defer fake.healthyMutex.RUnlock()
	return len(fake.healthyArgsForCall)
}

func (fake *FakeBackends) HealthyReturns(result1 <-chan switchboard.Backend) {
	fake.HealthyStub = nil
	fake.healthyReturns = struct {
		result1 <-chan switchboard.Backend
	}{result1}
}

var _ switchboard.Backends = new(FakeBackends)
