// This file was generated by counterfeiter
package monitorfakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/switchboard/runner/monitor"
)

type FakeCmdRunner struct {
	RunStub        func(name string, cmd ...string) ([]byte, error)
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		name string
		cmd  []string
	}
	runReturns struct {
		result1 []byte
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCmdRunner) Run(name string, cmd ...string) ([]byte, error) {
	fake.runMutex.Lock()
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		name string
		cmd  []string
	}{name, cmd})
	fake.recordInvocation("Run", []interface{}{name, cmd})
	fake.runMutex.Unlock()
	if fake.RunStub != nil {
		return fake.RunStub(name, cmd...)
	} else {
		return fake.runReturns.result1, fake.runReturns.result2
	}
}

func (fake *FakeCmdRunner) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeCmdRunner) RunArgsForCall(i int) (string, []string) {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.runArgsForCall[i].name, fake.runArgsForCall[i].cmd
}

func (fake *FakeCmdRunner) RunReturns(result1 []byte, result2 error) {
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeCmdRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeCmdRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ monitor.CmdRunner = new(FakeCmdRunner)
