// This file was generated by counterfeiter
package monitorfakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/switchboard/runner/monitor"
)

type FakeMonitor struct {
	MonitorStub        func(<-chan interface{})
	monitorMutex       sync.RWMutex
	monitorArgsForCall []struct {
		arg1 <-chan interface{}
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMonitor) Monitor(arg1 <-chan interface{}) {
	fake.monitorMutex.Lock()
	fake.monitorArgsForCall = append(fake.monitorArgsForCall, struct {
		arg1 <-chan interface{}
	}{arg1})
	fake.recordInvocation("Monitor", []interface{}{arg1})
	fake.monitorMutex.Unlock()
	if fake.MonitorStub != nil {
		fake.MonitorStub(arg1)
	}
}

func (fake *FakeMonitor) MonitorCallCount() int {
	fake.monitorMutex.RLock()
	defer fake.monitorMutex.RUnlock()
	return len(fake.monitorArgsForCall)
}

func (fake *FakeMonitor) MonitorArgsForCall(i int) <-chan interface{} {
	fake.monitorMutex.RLock()
	defer fake.monitorMutex.RUnlock()
	return fake.monitorArgsForCall[i].arg1
}

func (fake *FakeMonitor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.monitorMutex.RLock()
	defer fake.monitorMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeMonitor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ monitor.Monitor = new(FakeMonitor)
