// This file was generated by counterfeiter
package modelsfakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/switchboard/models"
)

type FakeBackends struct {
	AllStub        func() <-chan models.Backend
	allMutex       sync.RWMutex
	allArgsForCall []struct{}
	allReturns     struct {
		result1 <-chan models.Backend
	}
	ActiveStub        func() models.Backend
	activeMutex       sync.RWMutex
	activeArgsForCall []struct{}
	activeReturns     struct {
		result1 models.Backend
	}
	SetHealthyStub        func(backend models.Backend)
	setHealthyMutex       sync.RWMutex
	setHealthyArgsForCall []struct {
		backend models.Backend
	}
	SetUnhealthyStub        func(backend models.Backend)
	setUnhealthyMutex       sync.RWMutex
	setUnhealthyArgsForCall []struct {
		backend models.Backend
	}
	HealthyStub        func() <-chan models.Backend
	healthyMutex       sync.RWMutex
	healthyArgsForCall []struct{}
	healthyReturns     struct {
		result1 <-chan models.Backend
	}
	AsJSONStub        func() interface{}
	asJSONMutex       sync.RWMutex
	asJSONArgsForCall []struct{}
	asJSONReturns     struct {
		result1 interface{}
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBackends) All() <-chan models.Backend {
	fake.allMutex.Lock()
	fake.allArgsForCall = append(fake.allArgsForCall, struct{}{})
	fake.recordInvocation("All", []interface{}{})
	fake.allMutex.Unlock()
	if fake.AllStub != nil {
		return fake.AllStub()
	} else {
		return fake.allReturns.result1
	}
}

func (fake *FakeBackends) AllCallCount() int {
	fake.allMutex.RLock()
	defer fake.allMutex.RUnlock()
	return len(fake.allArgsForCall)
}

func (fake *FakeBackends) AllReturns(result1 <-chan models.Backend) {
	fake.AllStub = nil
	fake.allReturns = struct {
		result1 <-chan models.Backend
	}{result1}
}

func (fake *FakeBackends) Active() models.Backend {
	fake.activeMutex.Lock()
	fake.activeArgsForCall = append(fake.activeArgsForCall, struct{}{})
	fake.recordInvocation("Active", []interface{}{})
	fake.activeMutex.Unlock()
	if fake.ActiveStub != nil {
		return fake.ActiveStub()
	} else {
		return fake.activeReturns.result1
	}
}

func (fake *FakeBackends) ActiveCallCount() int {
	fake.activeMutex.RLock()
	defer fake.activeMutex.RUnlock()
	return len(fake.activeArgsForCall)
}

func (fake *FakeBackends) ActiveReturns(result1 models.Backend) {
	fake.ActiveStub = nil
	fake.activeReturns = struct {
		result1 models.Backend
	}{result1}
}

func (fake *FakeBackends) SetHealthy(backend models.Backend) {
	fake.setHealthyMutex.Lock()
	fake.setHealthyArgsForCall = append(fake.setHealthyArgsForCall, struct {
		backend models.Backend
	}{backend})
	fake.recordInvocation("SetHealthy", []interface{}{backend})
	fake.setHealthyMutex.Unlock()
	if fake.SetHealthyStub != nil {
		fake.SetHealthyStub(backend)
	}
}

func (fake *FakeBackends) SetHealthyCallCount() int {
	fake.setHealthyMutex.RLock()
	defer fake.setHealthyMutex.RUnlock()
	return len(fake.setHealthyArgsForCall)
}

func (fake *FakeBackends) SetHealthyArgsForCall(i int) models.Backend {
	fake.setHealthyMutex.RLock()
	defer fake.setHealthyMutex.RUnlock()
	return fake.setHealthyArgsForCall[i].backend
}

func (fake *FakeBackends) SetUnhealthy(backend models.Backend) {
	fake.setUnhealthyMutex.Lock()
	fake.setUnhealthyArgsForCall = append(fake.setUnhealthyArgsForCall, struct {
		backend models.Backend
	}{backend})
	fake.recordInvocation("SetUnhealthy", []interface{}{backend})
	fake.setUnhealthyMutex.Unlock()
	if fake.SetUnhealthyStub != nil {
		fake.SetUnhealthyStub(backend)
	}
}

func (fake *FakeBackends) SetUnhealthyCallCount() int {
	fake.setUnhealthyMutex.RLock()
	defer fake.setUnhealthyMutex.RUnlock()
	return len(fake.setUnhealthyArgsForCall)
}

func (fake *FakeBackends) SetUnhealthyArgsForCall(i int) models.Backend {
	fake.setUnhealthyMutex.RLock()
	defer fake.setUnhealthyMutex.RUnlock()
	return fake.setUnhealthyArgsForCall[i].backend
}

func (fake *FakeBackends) Healthy() <-chan models.Backend {
	fake.healthyMutex.Lock()
	fake.healthyArgsForCall = append(fake.healthyArgsForCall, struct{}{})
	fake.recordInvocation("Healthy", []interface{}{})
	fake.healthyMutex.Unlock()
	if fake.HealthyStub != nil {
		return fake.HealthyStub()
	} else {
		return fake.healthyReturns.result1
	}
}

func (fake *FakeBackends) HealthyCallCount() int {
	fake.healthyMutex.RLock()
	defer fake.healthyMutex.RUnlock()
	return len(fake.healthyArgsForCall)
}

func (fake *FakeBackends) HealthyReturns(result1 <-chan models.Backend) {
	fake.HealthyStub = nil
	fake.healthyReturns = struct {
		result1 <-chan models.Backend
	}{result1}
}

func (fake *FakeBackends) AsJSON() interface{} {
	fake.asJSONMutex.Lock()
	fake.asJSONArgsForCall = append(fake.asJSONArgsForCall, struct{}{})
	fake.recordInvocation("AsJSON", []interface{}{})
	fake.asJSONMutex.Unlock()
	if fake.AsJSONStub != nil {
		return fake.AsJSONStub()
	} else {
		return fake.asJSONReturns.result1
	}
}

func (fake *FakeBackends) AsJSONCallCount() int {
	fake.asJSONMutex.RLock()
	defer fake.asJSONMutex.RUnlock()
	return len(fake.asJSONArgsForCall)
}

func (fake *FakeBackends) AsJSONReturns(result1 interface{}) {
	fake.AsJSONStub = nil
	fake.asJSONReturns = struct {
		result1 interface{}
	}{result1}
}

func (fake *FakeBackends) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.allMutex.RLock()
	defer fake.allMutex.RUnlock()
	fake.activeMutex.RLock()
	defer fake.activeMutex.RUnlock()
	fake.setHealthyMutex.RLock()
	defer fake.setHealthyMutex.RUnlock()
	fake.setUnhealthyMutex.RLock()
	defer fake.setUnhealthyMutex.RUnlock()
	fake.healthyMutex.RLock()
	defer fake.healthyMutex.RUnlock()
	fake.asJSONMutex.RLock()
	defer fake.asJSONMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeBackends) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ models.Backends = new(FakeBackends)
